version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: umbrel-arr-qbittorrent_server_1
      APP_PORT: 8080
  server:
    image: lscr.io/linuxserver/qbittorrent:latest@sha256:d8488fb24969bb0954cf64a1ca1cf7a763031641ba4246734964faea6f0b807a
    restart: on-failure
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: ${TZ:-Etc/UTC}
      WEBUI_PORT: "8080"
      TORRENTING_PORT: "6881"
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
