version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: umbrel-arr-privado-vpn_server_1
      APP_PORT: 8080
  server:
    image: ghcr.io/umbrel-arr/privado-proxy:1.2.5@sha256:fd4246bc4c3b7a71d70f7ca78d76b9b2d9a044e248288d19ef566cec46d5db65
    restart: on-failure
    cap_add: [NET_ADMIN]
    sysctls:
      net.ipv4.conf.all.src_valid_mark: "1"
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      TZ: ${TZ:-Etc/UTC}
      SOCK_PORT: "1080"
      DASHBOARD_ENABLED: "true"
      DASHBOARD_PORT: "8080"
      PRIVADO_USERNAME: ""
      PRIVADO_PASSWORD: ""
      PRIVADO_SERVER: ""
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
